//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gallery_application
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilarr
    {
        public int id { get; set; }
        public string k_adi { get; set; }
        public string ad_soyad { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
        public string sifre { get; set; }
        public string rol { get; set; }
    }
}
